### ISSUE TITLE
Crash on inline image

### ISSUE THREAD

**Issue by Hodapp87** [42wim/matterbridge-plus#29]
I just set up from https://github.com/42wim/matterbridge-plus/releases/tag/v0.3.1 on Mattermost 3.0.3. Upon pasting an inline image into the channel, I saw the following in the debug output:

```
DEBU[2016-06-05T23:32:32-04:00] <-mattermost channel: testing &model.Post{Id:"4zhdzpgfcpnz9dj3rnw66j8cwc", CreateAt:1465183952893, UpdateAt:1465183952893, DeleteAt:0, UserId:"gng3qx853b8zdf1wf3j47n957e", ChannelId:"dnxsb47yotrx5fz4wj4ey718yw", RootId:"", ParentId:"", OriginalId:"", Message:"", Type:"", Props:model.StringInterface{}, Hashtags:"", Filenames:model.StringArray{"/dnxsb47yotrx5fz4wj4ey718yw/gng3qx853b8zdf1wf3j47n957e/z5641upx6ifatkruo4yikuwmaa/fabcam.jpg"}, PendingPostId:"gng3qx853b8zdf1wf3j47n957e:1465183925071"} &model.Message{TeamId:"13zhum79f7ggpxukc6oif5i63h", ChannelId:"dnxsb47yotrx5fz4wj4ey718yw", UserId:"gng3qx853b8zdf1wf3j47n957e", Action:"posted", Props:map[string]string{"post":"{\"id\":\"4zhdzpgfcpnz9dj3rnw66j8cwc\",\"create_at\":1465183952893,\"update_at\":1465183952893,\"delete_at\":0,\"user_id\":\"gng3qx853b8zdf1wf3j47n957e\",\"channel_id\":\"dnxsb47yotrx5fz4wj4ey718yw\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"filenames\":[\"/dnxsb47yotrx5fz4wj4ey718yw/gng3qx853b8zdf1wf3j47n957e/z5641upx6ifatkruo4yikuwmaa/fabcam.jpg\"],\"pending_post_id\":\"gng3qx853b8zdf1wf3j47n957e:1465183925071\"}", "mentions":"[\"i7z7ogtj8j8kume3jjhmdu31cy\"]", "channel_id":"dnxsb47yotrx5fz4wj4ey718yw", "parent_id":"", "teammate_id":"yxw3nn8dobdh5x64tquiksfphr", "image":"true", "otherFile":"true", "channel_type":"O"}}  module=mattermost
panic: runtime error: index out of range

goroutine 32 [running]:
panic(0x9342e0, 0xc820010070)
        /nasfs/users/u0022146/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
    github.com/42wim/matterbridge-plus/bridge.(*Bridge).handleMatter(0xc82007f7a0)
            /tmp/go7/src/github.com/42wim/matterbridge-plus/bridge/bridge.go:398 +0x1236
        created by github.com/42wim/matterbridge-plus/bridge.NewBridge
                /tmp/go7/src/github.com/42wim/matterbridge-plus/bridge/bridge.go:107 +0x59a
```

(sorry for long line, but I don't know how else to wrap it)

**Comment by 42wim** [comment]
Thanks for reporting, (it only crashes when you don't put a text by the image). Images (attachments) are not relayed to IRC for now.
Fixed in master
